apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.website2.si.configmap.name2 }}
data:
  SERVER_PORT_WS: "{{ .Values.website2.si.SERVER_PORT_WS }}"
  SERVER_PORT_UI: "{{ .Values.website2.si.SERVER_PORT_UI }}"
  SERVER_PORT_DB: "{{ .Values.website2.si.SERVER_PORT_DB }}"
  SERVER_PORT_SI: "{{ .Values.website2.si.SERVER_PORT_SI }}"
  SERVER_PORT_SI_UI: "{{ .Values.website2.si.SERVER_PORT_SI_UI }}"
  SI_SERVER_PORT: "{{ .Values.website2.si.SI_SERVER_PORT }}"
  SI_SERVER_HOST: "{{ .Values.website2.si.SI_SERVER_HOST }}"
  WS_URL: "{{ .Values.website2.si.WS_URL }}"
  WS_SI_URL: "{{ .Values.website2.si.WS_SI_URL }}"
  DCAF_IMAGE_TAG: "{{ .Values.website2.si.DCAF_IMAGE_TAG }}"

