apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.website.ui.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  WS_URL: "{{ .Values.website.ui.WS_URL }}"
  WS_SI_URL: "{{ .Values.website.ui.WS_SI_URL }}"
  UI_URL: "{{ .Values.website.ui.UI_URL }}"
