apiVersion: v1
appVersion: "1.16.0"
description: A Helm chart for Kubernetes.
name: dcaf-app
version: 0.1.0
source:
  - https://github.com/Maroon20-code/helm-chart/tree/dcaf-chart
maintainers:
  - email: marwenghodben@gmail.com
    name: Marwen