apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.website2.si.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "si-label" . | nindent 3 }}
spec:
  replicas: {{ .Values.website2.si.deployment.replicas | int }}
  selector:
    matchLabels: {{- include "si-label" . | nindent 5 }}
  template:
    metadata:
      labels: {{- include "si-label" . | nindent 7 }}
    spec:
      containers:
      - name: dcaf-si
        image: {{ .Values.images.registry }}/dcaf_si:{{ .Values.images.tag }}
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.website2.si.SI_SERVER_PORT }}
        envFrom:
          - configMapRef:
              name: {{ .Values.website2.si.configmap.name2 }}
      imagePullSecrets:
      - name: {{ .Values.harbor_sercret }}
