apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secret_db.POSTGRES_PASSWORD }}
  POSTGRES_USER: {{ .Values.secret_db.POSTGRES_USER }}
  POSTGRES_DB: {{ .Values.secret_db.POSTGRES_DB }}